title: Sarthak Kasturi
email: sarthakkasturi@gmail.com
url: "https://kasturisarthak.github.io" # the base hostname & protocol for your site
twitter_username: yourtwitter
github_username: kasturisarthak
linkedin_username: sarthakkasturi

# Build settings
theme: jekyll-theme-minimal

# Navigation links
nav_links:
  - name: "About"
    link: "/about"
  - name: "Resume"
    link: "/resume"

# Social Links
