baseURL = "https://kasturisarthak.github.io"
title = "Sarthak Kasturi"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Sarthak Kasturi"
description = "Sarthak Kasturi's Profile"
keywords = "blog,developer,personal,coder,computer,azure,cloud"
info = "Full Stack Software Developer | Cloud & DevOps Engineer"
avatarURL = "images/profile.jpg"
#gravatar = "images/profile.jpg"
footerContent = "<cite>There may be people that have more talent than you, but there's no excuse for anyone to work harder than you</cite>"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = true
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[params.googleTagManager]
id = "6zz4m7owod"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "E-Mail"
icon = "fa fa-envelope"
weight = 1
url = "mailto:kasturi.sarthak1@gmail.com"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/kasturisarthak"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/sarthakkasturi/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 5
url = "https://x.com/kasturisarthak1"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 6
url = "https://www.instagram.com/sarthakkasturi/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

#[[languages.en.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

#[[languages.en.menu.main]]
#name = "Research"
#weight = 3
#url = "research/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "resume.pdf"
